# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Hannah YoungEun An
title: URCS Doctoral Student
email: yan2@ur.rochester.edu
website: anyhannah.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: hannah0n
github_username:  anyhannah
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: hannah-an
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a PhD candidate at the University of Rochester in [Computer Science](https://www.cs.rochester.edu/). My research spans across Natural Language Understanding/Processing, Computational Linguistics, and Artificial Intelligence. Specifically, I work on mining commonsense knowledge and organizing world knowledge into schemas to reflect the relational understanding between entities as well as between knowledge and action with [Len Schubert](https://www.cs.rochester.edu/~schubert/). I also work on detecting and recovering semantically compressed forms, including ellipsis, with [Aaron Steven White](http://aaronstevenwhite.io/).

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak
        title: Lexical knowledge and object schema acquisition
        # link_text: Project Website
        quote: >
          Jo wanted to hang up the frame. Should we expect him to go looking for a nail or a TV?
        description: | # this will include new lines to allow paragraphs
          I work on obtaining commonly assumed knowledge about objects from various sources and representing the acquired knowledge in a formalized knowledge representation, called a schema. My work focuses on capturing **lexical knowledge**&mdash;such as hypernyms, parts, materials, and usage information&mdash;to enable human-like reasoning in AI.
      - layout: top-middle
        border: weak
        title: Commonsense reasoning dataset
        quote: >
          Which is less likely to be, made at least partially, of a material that is a constituent of a ping pong paddle: a computer mouse or a tuning fork? 
        description: |
          I create a **manually curated dataset** of binary-choice questions about shared materials between objects. Each entry in the dataset is carefully reviewed to challenge language models to consider detailed information on artifact parts and material compositions.
      - layout: top-middle
        border: weak
        title: Semantically compressed forms
        quote: >
          What do you mean by you think so?
        description: |
         I also work on making the underlying meaning of semantically compressed forms explicit in text. The scope of the project extends beyond **elliptical utterances**, such as verb phrase ellipsis, to include non-elliptical referring expressions, such as null complement anaphora.
      - layout: top-middle
        title: Neg(ation)-raising
        link: megaattitude.io/projects/mega-negraising
        quote: >
          Jo doesn’t think that Bo left. Does Jo think that Bo didn't leave?
        description: |
         I was involved in [FACTS.lab](http://factslab.io/)'s [MegaAttitude Project](http://megaattitude.io/) for building lexicon-scale datasets from crowdsourcing and studying the **semantic contribution** of lexical items and syntactic structures.

  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: "2024"
        description: | # this will include new lines to allow paragraphs
            **Hannah Y. An**, and Lenhart K. Schubert. (2024). [Large Language Models as a Tool for Mining Object Knowledge](https://doi.org/10.48550/arXiv.2410.12959). [<mark>paper</mark>](https://arxiv.org/pdf/2410.12959)
      - layout: left
        title: 
        description: |
            Jiacan Yu, **Hannah Y. An**, and Lenhart K. Schubert. (2024). Language Models Benefit from Preparation with Elicited Knowledge. [<mark>dataset</mark>](https://huggingface.co/datasets/jjjyu48/SharedMaterialQA)
      - layout: left
        title: 
        description: |
            William Gantt, Shabnam Behzad, **Hannah YoungEun An**, Yunmo Chen, Aaron Steven White, Benjamin Van Durme, and Mahsa Yarmohammadi. (2024). [MultiMUC: Multilingual Template Filling on MUC-4](https://aclanthology.org/2024.eacl-long.21/). In *Proceedings of the 18th Conference of the European Chapter of the Association for Computational Linguistics (Volume 1: Long Papers)*, pages 349-368, St. Julian’s, Malta. Association for Computational Linguistics. [<mark>paper</mark>](https://aclanthology.org/2024.eacl-long.21.pdf)
      - layout: left
        title: "2023"
        description: |
            James Allen, **Hannah An**, Ritwik  Bose, Will de Beaumont, and Choh Man Teng. (2023). [COLLIE: a broad-coverage ontology and lexicon of verbs in English](https://doi.org/10.1007/s10579-022-09600-9). In *Language Resources and Evaluation*, *57*(1), pages 57-86. Springer Nature. [<mark>paper</mark>](https://link.springer.com/content/pdf/10.1007/s10579-022-09600-9.pdf)
      - layout: left
        title: "2020"
        description: |
            James Allen, **Hannah An**, Ritwik  Bose, Will de Beaumont, and Choh Man Teng. (2020). [A Broad-Coverage Deep Semantic Lexicon for Verbs](https://aclanthology.org/2020.lrec-1.396/). In *Proceedings of the Twelfth Language Resources and Evaluation Conference*, pages 3243–3251, Marseille, France. European Language Resources Association. [<mark>paper</mark>](https://aclanthology.org/2020.lrec-1.396.pdf)
      - layout: left
        title: 
        description: |
            **Hannah Youngeun An** and Aaron Steven White. (2020). [The lexical and grammatical sources of neg-raising inferences](https://aclanthology.org/2020.scil-1.45/). In *Proceedings of the Society for Computation in Linguistics*, pages 386-399, New York, New York. Association for Computational Linguistics. [<mark>paper</mark>](https://aclanthology.org/2020.scil-1.45.pdf) [<mark>poster</mark>](https://anyhannah.github.io/assets/poster_SCiL2020.pdf)

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Rochester
        caption: 2019 - Present
        sub_title: PhD Computer Science
        description: Specialized in Artificial Intelligence, I am currently working on making implicit content explicit and acquiring lexical knowledge for AI systems to support the reasoning process.
      - layout: left
        title: University of Rochester
        caption: 2019 - 2021
        sub_title: MS Computer Science
        description: I worked on aligning and developing ontologies with a deep semantic lexicon to support reasoning about commonsense knowledge, supervised by [James Allen](https://www.cs.rochester.edu/~james/).
      - layout: left
        title: University of Rochester
        caption: 2017 - 2019
        sub_title: MS Computational Linguistics
        description: During my first two years in Rochester, many courses taught me key skills required in NLP and ML. As a part of the master's degree, I completed a final project 'Neg-raising inference and its syntactic contexts' supervised by [Aaron Steven White](http://aaronstevenwhite.io/).
      - layout: left
        title: University of Washington
        caption: 2012 - 2017
        sub_title: MA Linguistics
        description: I graduated with Departmental Honors in Linguistics, with an unweighted 4.0 GPA in the courses offered from the department and with an honors thesis 'Characteristic determiners vs. adjectives in Korean' supervised by [Toshiyuki Ogihara](https://faculty.washington.edu/ogihara/).
      - layout: left
        title: University of Washington
        caption: 2012 - 2017
        sub_title: BS Applied and Computational Mathematical Sciences
        description: My undergraduate degree with specialization in Scientific Computing and Numerical Algorithms prepared me to acquire a strong background in Math. Independent of my major program, I completed a minor in Philosophy as well.

  - title: Teaching
    layout: text
    content: |
        - Teaching Assistant: CSC 247/447 Natural Language Processing (Spring 2021, University of Rochester)
        - Teaching Assistant: CSC 442 Introduction to Artificial Intelligence (Fall 2020, University of Rochester)
        - Teaching Assistant: CSC 247/447 Natural Language Processing (Spring 2020, University of Rochester)
        - Teaching Assistant: LIN 110 Introduction to Linguistic Analysis (Spring 2018, University of Rochester)
        - Korean Tutor @ CLUE Academic Support Program (Fall 2016 - Spring 2017, University of Washington)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
